/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import com.sun.glass.ui.Window;
import entities.Lot;
import entities.Piece;
import java.awt.event.WindowEvent;
import javax.swing.JOptionPane;
import javax.swing.text.html.Option;
import managerBDD.GestionPiece;
import model.ModeleComboBoxLot;
import model.ModeleTableauPieces;
import renderer.RenduComboBoxLot;

/**
 *
 * @author BOUGHANMI
 */
public class CONTROLEUR extends javax.swing.JFrame {


    public CONTROLEUR() {
        initComponents();
        this.panCommentaire.setVisible(false);
        this.labLotEnCours.setText(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        panSaisie = new javax.swing.JPanel();
        labHT = new javax.swing.JLabel();
        labHL = new javax.swing.JLabel();
        labBT = new javax.swing.JLabel();
        labBL = new javax.swing.JLabel();
        txtSaisieHT = new javax.swing.JTextField();
        txtSaisieHL = new javax.swing.JTextField();
        txtSaisieBT = new javax.swing.JTextField();
        txtSaisieBL = new javax.swing.JTextField();
        labSaisirLesMesures = new javax.swing.JLabel();
        butOKMesures = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabPieces = new javax.swing.JTable();
        panControleVisuel = new javax.swing.JPanel();
        labControleVisuel = new javax.swing.JLabel();
        radOK = new javax.swing.JRadioButton();
        radRebut = new javax.swing.JRadioButton();
        panCommentaire = new javax.swing.JPanel();
        labCommentaire = new javax.swing.JLabel();
        txtCommentaire = new javax.swing.JTextField();
        panLot = new javax.swing.JPanel();
        butFinLot = new javax.swing.JButton();
        comChoisirLot = new javax.swing.JComboBox();
        butValiderLot = new javax.swing.JButton();
        labTitreLotEnCours = new javax.swing.JLabel();
        labLotEnCours = new javax.swing.JLabel();
        labTitreFenetre = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panSaisie.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panSaisie.setToolTipText("");

        labHT.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        labHT.setText("HT :");

        labHL.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        labHL.setText("HL :");

        labBT.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        labBT.setText("BT :");

        labBL.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        labBL.setText("BL :");

        txtSaisieHT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSaisieHTActionPerformed(evt);
            }
        });

        txtSaisieHL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSaisieHLActionPerformed(evt);
            }
        });

        txtSaisieBL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSaisieBLActionPerformed(evt);
            }
        });

        labSaisirLesMesures.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        labSaisirLesMesures.setText("Saisir les mesures :");

        butOKMesures.setText("OK");
        butOKMesures.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butOKMesuresActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panSaisieLayout = new javax.swing.GroupLayout(panSaisie);
        panSaisie.setLayout(panSaisieLayout);
        panSaisieLayout.setHorizontalGroup(
            panSaisieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panSaisieLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(panSaisieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labSaisirLesMesures, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panSaisieLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(panSaisieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labHL, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labHT, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labBL)
                            .addComponent(labBT))
                        .addGap(60, 60, 60)
                        .addGroup(panSaisieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtSaisieHL, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSaisieBL, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSaisieHT, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSaisieBT, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 94, Short.MAX_VALUE)
                .addComponent(butOKMesures, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panSaisieLayout.setVerticalGroup(
            panSaisieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panSaisieLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labSaisirLesMesures, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panSaisieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labHL)
                    .addComponent(txtSaisieHL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(panSaisieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labHT, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSaisieHT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panSaisieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labBL)
                    .addComponent(txtSaisieBL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(panSaisieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(butOKMesures, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labBT)
                    .addComponent(txtSaisieBT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(75, 75, 75))
        );

        tabPieces.setModel(new ModeleTableauPieces());
        tabPieces.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane1.setViewportView(tabPieces);

        panControleVisuel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        labControleVisuel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labControleVisuel.setText("Contrôle visuel :");

        buttonGroup1.add(radOK);
        radOK.setSelected(true);
        radOK.setText("OK");
        radOK.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        radOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radOKActionPerformed(evt);
            }
        });

        buttonGroup1.add(radRebut);
        radRebut.setText("Rebut");
        radRebut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radRebutActionPerformed(evt);
            }
        });

        panCommentaire.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        labCommentaire.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        labCommentaire.setText("Commentaire :");

        txtCommentaire.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtCommentaire.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCommentaireActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panCommentaireLayout = new javax.swing.GroupLayout(panCommentaire);
        panCommentaire.setLayout(panCommentaireLayout);
        panCommentaireLayout.setHorizontalGroup(
            panCommentaireLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panCommentaireLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panCommentaireLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panCommentaireLayout.createSequentialGroup()
                        .addComponent(labCommentaire, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(txtCommentaire))
                .addContainerGap())
        );
        panCommentaireLayout.setVerticalGroup(
            panCommentaireLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panCommentaireLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labCommentaire)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addComponent(txtCommentaire, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout panControleVisuelLayout = new javax.swing.GroupLayout(panControleVisuel);
        panControleVisuel.setLayout(panControleVisuelLayout);
        panControleVisuelLayout.setHorizontalGroup(
            panControleVisuelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panControleVisuelLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(labControleVisuel, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panControleVisuelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(radRebut)
                    .addComponent(radOK, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31))
            .addGroup(panControleVisuelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panCommentaire, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panControleVisuelLayout.setVerticalGroup(
            panControleVisuelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panControleVisuelLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(panControleVisuelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labControleVisuel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(radOK))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(radRebut)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addComponent(panCommentaire, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        panLot.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        butFinLot.setText("Fin du lot");
        butFinLot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butFinLotActionPerformed(evt);
            }
        });

        comChoisirLot.setModel(new ModeleComboBoxLot());
        comChoisirLot.setRenderer(new RenduComboBoxLot());
        comChoisirLot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comChoisirLotActionPerformed(evt);
            }
        });

        butValiderLot.setText("OK");
        butValiderLot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butValiderLotActionPerformed(evt);
            }
        });

        labTitreLotEnCours.setText("Lot en cours : ");

        labLotEnCours.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout panLotLayout = new javax.swing.GroupLayout(panLot);
        panLot.setLayout(panLotLayout);
        panLotLayout.setHorizontalGroup(
            panLotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panLotLayout.createSequentialGroup()
                .addGroup(panLotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panLotLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(panLotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panLotLayout.createSequentialGroup()
                                .addComponent(labLotEnCours, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 184, Short.MAX_VALUE)
                                .addComponent(butFinLot, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panLotLayout.createSequentialGroup()
                                .addComponent(labTitreLotEnCours, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(panLotLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(comChoisirLot, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(butValiderLot, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        panLotLayout.setVerticalGroup(
            panLotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panLotLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panLotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comChoisirLot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(butValiderLot))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addComponent(labTitreLotEnCours, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(panLotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panLotLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(butFinLot))
                    .addGroup(panLotLayout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(labLotEnCours, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20))
        );

        labTitreFenetre.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        labTitreFenetre.setText("Contrôle Pièces");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(panLot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(panControleVisuel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(panSaisie, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(71, 71, 71)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 671, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(426, 426, 426)
                        .addComponent(labTitreFenetre)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labTitreFenetre)
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panLot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(panControleVisuel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panSaisie, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1))
                .addGap(27, 27, 27))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtSaisieHLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSaisieHLActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSaisieHLActionPerformed

    private void txtSaisieBLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSaisieBLActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSaisieBLActionPerformed

    private void txtSaisieHTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSaisieHTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSaisieHTActionPerformed

    private void butValiderLotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butValiderLotActionPerformed
        if (comChoisirLot.getSelectedItem() != null)
        {           
         labLotEnCours.setText(Integer.toString((((Lot)comChoisirLot.getSelectedItem()).getIdLot())));           
        }
        else
        {
            JOptionPane.showMessageDialog(this, "Selectionnez un lot !","Contrôle Pièces", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_butValiderLotActionPerformed
    
    private void butFinLotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butFinLotActionPerformed
         if (labLotEnCours.getText() != null)
         {
             JOptionPane.showMessageDialog(this, managerBDD.GestionLots.finLot(Integer.parseInt(labLotEnCours.getText())));
             labLotEnCours.setText(null);
             
         }
         else
         {
             JOptionPane.showMessageDialog(this, "Aucun lot en cours !","Contrôle Pièces", JOptionPane.WARNING_MESSAGE);
         }
         
         ModeleComboBoxLot m = (ModeleComboBoxLot) this.comChoisirLot.getModel();
         m.refreshModel();
    }//GEN-LAST:event_butFinLotActionPerformed

    private void radRebutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radRebutActionPerformed
     this.panCommentaire.setVisible(true);
     this.txtCommentaire.requestFocus();
     this.txtSaisieHT.setEditable(false);
     this.txtSaisieHL.setEditable(false);
     this.txtSaisieBT.setEditable(false);
     this.txtSaisieBL.setEditable(false);
    }//GEN-LAST:event_radRebutActionPerformed

    private void radOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radOKActionPerformed
    this.panCommentaire.setVisible(false);
    this.txtSaisieHT.setEditable(true);
    this.txtSaisieHL.setEditable(true);
    this.txtSaisieBT.setEditable(true);
    this.txtSaisieBL.setEditable(true);
    }//GEN-LAST:event_radOKActionPerformed

    private void txtCommentaireActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCommentaireActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCommentaireActionPerformed

    private void comChoisirLotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comChoisirLotActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comChoisirLotActionPerformed

    private void butOKMesuresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butOKMesuresActionPerformed
        if (this.radRebut.isSelected() && !tools.Tools.isNull(labLotEnCours.getText()))
        {
            if(tools.Tools.isNull(this.txtCommentaire.getText()))
            {   
               JOptionPane.showMessageDialog(this, "Saisie du commentaire incorrecte !","Contrôle Pièces", JOptionPane.WARNING_MESSAGE);
            }
            else
            {
                entities.Piece p = new Piece (0, -1, -1, -1, 1, null, Integer.parseInt(this.labLotEnCours.getText()), this.txtCommentaire.getText());
                GestionPiece.ajouterPiece(p);
            }
        }
        else if(this.radOK.isSelected() && !tools.Tools.isNull(labLotEnCours.getText()))
        {
            if(!tools.Tools.mesureCorrecte(this.txtSaisieHT.getText()) || !tools.Tools.mesureCorrecte(this.txtSaisieHL.getText()) || 
                    !tools.Tools.mesureCorrecte(this.txtSaisieBT.getText()) || !tools.Tools.mesureCorrecte(this.txtSaisieBL.getText()))
            {
                JOptionPane.showMessageDialog(this, "Saisie des mesures incorrecte !","Contrôle Pièces",JOptionPane.WARNING_MESSAGE);
            }
            else
            {
                entities.Piece p = new Piece(0, Float.parseFloat(this.txtSaisieHT.getText()), Float.parseFloat(this.txtSaisieHL.getText()), 
                        Float.parseFloat(this.txtSaisieBT.getText()), Float.parseFloat(this.txtSaisieBL.getText()),null , Integer.parseInt(this.labLotEnCours.getText()), null );
                
                GestionPiece.ajouterPiece(p);
            }
        }
        else
        {
             JOptionPane.showMessageDialog(this, "Selectionnez un lot !","Contrôle Pièces", JOptionPane.WARNING_MESSAGE);
        }
        ModeleTableauPieces m = (ModeleTableauPieces) this.tabPieces.getModel();
        m.refreshModel();
    }//GEN-LAST:event_butOKMesuresActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton butFinLot;
    private javax.swing.JButton butOKMesures;
    private javax.swing.JButton butValiderLot;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JComboBox comChoisirLot;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labBL;
    private javax.swing.JLabel labBT;
    private javax.swing.JLabel labCommentaire;
    private javax.swing.JLabel labControleVisuel;
    private javax.swing.JLabel labHL;
    private javax.swing.JLabel labHT;
    private javax.swing.JLabel labLotEnCours;
    private javax.swing.JLabel labSaisirLesMesures;
    private javax.swing.JLabel labTitreFenetre;
    private javax.swing.JLabel labTitreLotEnCours;
    private javax.swing.JPanel panCommentaire;
    private javax.swing.JPanel panControleVisuel;
    private javax.swing.JPanel panLot;
    private javax.swing.JPanel panSaisie;
    private javax.swing.JRadioButton radOK;
    private javax.swing.JRadioButton radRebut;
    private javax.swing.JTable tabPieces;
    private javax.swing.JTextField txtCommentaire;
    private javax.swing.JTextField txtSaisieBL;
    private javax.swing.JTextField txtSaisieBT;
    private javax.swing.JTextField txtSaisieHL;
    private javax.swing.JTextField txtSaisieHT;
    // End of variables declaration//GEN-END:variables
}
