/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import entities.Lot;
import entities.Stock;
import javax.swing.JOptionPane;
import managerBDD.ManagerCo;
import model.ListLotModel;

/**
 *
 * @author DJENADI
 */
public class LaunchedBatchFrame extends javax.swing.JFrame {

    private Stock stock;

    public LaunchedBatchFrame() {
        initComponents();
        //On set le modele sans lui passer de parametres pour selectionner toutes les demandes en cours
        this.listLotLances.setModel(new ListLotModel());

    }

    public LaunchedBatchFrame(Stock st) throws Exception {
        if (st == null) {
            throw new Exception("Le stock ne peut être nul");
        } else {
            this.stock = st;
            initComponents();
            //On set le modele en lui passant un parametre pour filtrer le resultat sur le modele selectionné
            this.listLotLances.setModel(new ListLotModel(this.stock));
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labLotLances = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listLotLances = new javax.swing.JList();
        butAnnuler = new javax.swing.JButton();
        labError = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        labLotLances.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        labLotLances.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labLotLances.setText("Liste des lots lancés");

        jScrollPane1.setViewportView(listLotLances);

        butAnnuler.setText("ANNULER");
        butAnnuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butAnnulerActionPerformed(evt);
            }
        });

        labError.setForeground(new java.awt.Color(255, 51, 51));
        labError.setText(" ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labLotLances, javax.swing.GroupLayout.PREFERRED_SIZE, 596, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(labError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 511, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(butAnnuler, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(labLotLances)
                .addGap(22, 22, 22)
                .addComponent(labError)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(butAnnuler, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void butAnnulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butAnnulerActionPerformed
        this.labError.setText(" ");
        Lot lot;
        lot = (Lot) this.listLotLances.getSelectedValue();
        String s = null;
        if (lot != null) {
            s = ManagerCo.deleteBatch(lot.getIdLot());
            JOptionPane.showMessageDialog(this, s);
            this.refreshList(lot);
        } else {
            this.labError.setText("Veuillez selectionner une ligne");
        }
    }//GEN-LAST:event_butAnnulerActionPerformed
    public void refreshList(Lot l){
        ListLotModel llm = (ListLotModel) this.listLotLances.getModel();
        llm.refreshmodel(l);
    }
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton butAnnuler;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labError;
    private javax.swing.JLabel labLotLances;
    private javax.swing.JList listLotLances;
    // End of variables declaration//GEN-END:variables
}
