/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import model.TableStockModel;

/**
 *
 * @author DJENADI
 */
public class LimitsPanel extends javax.swing.JPanel {

    /**
     * Creates new form LimitsPanel
     */
    public LimitsPanel() {
        initComponents();
        this.panModifSeuils.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabCtrlStock = new javax.swing.JTable();
        labGestionSeuil = new javax.swing.JLabel();
        butModifierSeuil = new javax.swing.JButton();
        labError = new javax.swing.JLabel();
        panModifSeuils = new javax.swing.JPanel();
        labModel = new javax.swing.JLabel();
        labCategorie = new javax.swing.JLabel();
        labSeuilActuel = new javax.swing.JLabel();
        labEtiqModel = new javax.swing.JLabel();
        labEtiqCateg = new javax.swing.JLabel();
        labEtiqSeuil = new javax.swing.JLabel();
        tfNvSeuil = new javax.swing.JTextField();
        butValidModif = new javax.swing.JButton();
        labEtiqNvSeuil = new javax.swing.JLabel();
        labTitModif = new javax.swing.JLabel();

        tabCtrlStock.setModel(new TableStockModel()
        );
        tabCtrlStock.getTableHeader().setResizingAllowed(false);
        tabCtrlStock.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tabCtrlStock);

        labGestionSeuil.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        labGestionSeuil.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labGestionSeuil.setText("Gestion des Seuils");

        butModifierSeuil.setText("MODIFIER UN SEUIL");
        butModifierSeuil.setToolTipText("Lancer une demande d'approvisionnement");
        butModifierSeuil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butModifierSeuilActionPerformed(evt);
            }
        });

        labError.setForeground(new java.awt.Color(255, 51, 51));
        labError.setText("  ");

        panModifSeuils.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        labModel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labModel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labModel.setText("test");

        labCategorie.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labCategorie.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labCategorie.setText("test");

        labSeuilActuel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labSeuilActuel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labSeuilActuel.setText("test");

        labEtiqModel.setForeground(new java.awt.Color(102, 102, 102));
        labEtiqModel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labEtiqModel.setText("Modèle");

        labEtiqCateg.setForeground(new java.awt.Color(102, 102, 102));
        labEtiqCateg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labEtiqCateg.setText("Categorie");

        labEtiqSeuil.setForeground(new java.awt.Color(102, 102, 102));
        labEtiqSeuil.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labEtiqSeuil.setText("Seuil Actuel");

        tfNvSeuil.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        tfNvSeuil.setText("Indiquez le nouveau seuil");

        butValidModif.setText("VALIDER");

        labEtiqNvSeuil.setForeground(new java.awt.Color(102, 102, 102));
        labEtiqNvSeuil.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labEtiqNvSeuil.setText("Nouveau Seuil");

        labTitModif.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labTitModif.setText("Modification du Seuil");

        javax.swing.GroupLayout panModifSeuilsLayout = new javax.swing.GroupLayout(panModifSeuils);
        panModifSeuils.setLayout(panModifSeuilsLayout);
        panModifSeuilsLayout.setHorizontalGroup(
            panModifSeuilsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panModifSeuilsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panModifSeuilsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labModel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labCategorie, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labSeuilActuel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labEtiqModel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labEtiqCateg, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                    .addComponent(labEtiqSeuil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tfNvSeuil)
                    .addComponent(butValidModif, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labEtiqNvSeuil, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labTitModif, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panModifSeuilsLayout.setVerticalGroup(
            panModifSeuilsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panModifSeuilsLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labTitModif)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labEtiqModel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labModel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(labEtiqCateg)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labCategorie, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labEtiqSeuil)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labSeuilActuel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(labEtiqNvSeuil)
                .addGap(5, 5, 5)
                .addComponent(tfNvSeuil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(butValidModif)
                .addGap(16, 16, 16))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labGestionSeuil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(labError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 666, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(butModifierSeuil, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                            .addComponent(panModifSeuils, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(labGestionSeuil)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labError)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(butModifierSeuil, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panModifSeuils, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addContainerGap(15, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void butModifierSeuilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butModifierSeuilActionPerformed
        //On set le label error à ""
        this.labError.setText(" ");
        //Si aucune ligne n'est selectionnée
        if (this.tabCtrlStock.getSelectedRow() != -1) {
            //On fait apparaître le panel modif
            this.panModifSeuils.setVisible(true);
            //On recupère le modele de la tabCtrlStock casté.
            TableStockModel model = (TableStockModel) tabCtrlStock.getModel();

            //On ouvre la frame approvisionnement
            //Pour lui faire passer l'objet Stock en paramètre, on utilise la methode getElementAt du modele qui nous renvoie un Stock.
            //getElementAt prend en paramètre un index. Ici, l'index est la getSelectedRow
            
        } else {
            //Sinon on set le label erreur
            this.labError.setText("Veuillez selectionner une ligne");
        }
    }//GEN-LAST:event_butModifierSeuilActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton butModifierSeuil;
    private javax.swing.JButton butValidModif;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labCategorie;
    private javax.swing.JLabel labError;
    private javax.swing.JLabel labEtiqCateg;
    private javax.swing.JLabel labEtiqModel;
    private javax.swing.JLabel labEtiqNvSeuil;
    private javax.swing.JLabel labEtiqSeuil;
    private javax.swing.JLabel labGestionSeuil;
    private javax.swing.JLabel labModel;
    private javax.swing.JLabel labSeuilActuel;
    private javax.swing.JLabel labTitModif;
    private javax.swing.JPanel panModifSeuils;
    private javax.swing.JTable tabCtrlStock;
    private javax.swing.JTextField tfNvSeuil;
    // End of variables declaration//GEN-END:variables
}
