/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import java.awt.event.WindowAdapter;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import managerBDD.ManagerLot;
import managerBDD.ManagerPresse;
import model.TablePresseModel;
import tools.Tools;

/**
 *
 * @author quent
 */
public class PUdemarrer extends javax.swing.JFrame {

    /**
     * Creates new form POPUPconfirmationDemarrer
     */
    public PUdemarrer() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        butOUI = new javax.swing.JButton();
        butNON = new javax.swing.JButton();
        labDemarrer = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        butOUI.setText("OUI");
        butOUI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butOUIActionPerformed(evt);
            }
        });

        butNON.setText("NON");
        butNON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butNONActionPerformed(evt);
            }
        });

        labDemarrer.setText("Confirmer Démarrage du Lot n° "+(int) RESP_PRODUCTION.getTabLot().getValueAt(RESP_PRODUCTION.getTabLot().getSelectedRow(), 0)+" sur la Presse n° "+(int) RESP_PRODUCTION.getTabPresse().getValueAt(RESP_PRODUCTION.getTabPresse().getSelectedRow(), 0)+" ?");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(butOUI, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                .addComponent(butNON, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
            .addComponent(labDemarrer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labDemarrer, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(butOUI, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(butNON, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void abonner(WindowAdapter wa){
        this.addWindowListener(wa);
      
    }
    
    
    private void butOUIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butOUIActionPerformed
    
        
        int idLot = (int) RESP_PRODUCTION.getTabLot().getValueAt(RESP_PRODUCTION.getTabLot().getSelectedRow(), 0);
        int idPresse = (int) RESP_PRODUCTION.getTabPresse().getValueAt(RESP_PRODUCTION.getTabPresse().getSelectedRow(), 0);
   
              if (Tools.isInf(idLot) && Tools.isInf(idPresse)) {

                JOptionPane.showMessageDialog(this, ManagerLot.demarrerLot(idLot, idPresse));
               this.dispose();

            }
    }//GEN-LAST:event_butOUIActionPerformed

    private void butNONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butNONActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_butNONActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PUdemarrer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PUdemarrer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PUdemarrer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PUdemarrer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PUdemarrer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton butNON;
    private javax.swing.JButton butOUI;
    private javax.swing.JLabel labDemarrer;
    // End of variables declaration//GEN-END:variables
}
