/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import entities.Presse;
import java.awt.event.WindowAdapter;
import javax.swing.JOptionPane;
import managerBDD.ManagerPresse;
import tools.Tools;

/**
 *
 * @author quent
 */
public class PUrehabiliter extends javax.swing.JFrame {

    /**
     * Creates new form PUrehabiliter
     */
    public PUrehabiliter() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labrehabiliter = new javax.swing.JLabel();
        butOui = new javax.swing.JButton();
        butNon = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labrehabiliter.setText("Voulez vous vraiment réhabiliter la Presse ?");

        butOui.setText("Oui");
        butOui.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butOuiActionPerformed(evt);
            }
        });

        butNon.setText("Non");
        butNon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butNonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(butOui, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(butNon, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(labrehabiliter))
                .addContainerGap(85, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(labrehabiliter)
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(butOui, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(butNon, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(66, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void butOuiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butOuiActionPerformed
        
    Presse p =(Presse) PanelMachine.listPresse.getSelectedValue();
     int numPresse = p.getNumPresse();
    
     if(Tools.isInf(numPresse))
     {
         JOptionPane.showMessageDialog(this, ManagerPresse.rehabiliterPresse(numPresse));
         this.dispose();
     }    
    }//GEN-LAST:event_butOuiActionPerformed

    private void butNonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butNonActionPerformed
     
        this.setVisible(false);
    }//GEN-LAST:event_butNonActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton butNon;
    private javax.swing.JButton butOui;
    private javax.swing.JLabel labrehabiliter;
    // End of variables declaration//GEN-END:variables

      public void abonner(WindowAdapter wa){
        this.addWindowListener(wa);
      
    }
}
