/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import entities.Presse;
import java.awt.event.WindowAdapter;
import javax.swing.JOptionPane;
import managerBDD.ManagerPresse;
import tools.Tools;

/**
 *
 * @author quent
 */
public class PUsupprimer extends javax.swing.JFrame {

    /**
     * Creates new form POPUPconfirmationSupprimer
     */
    public PUsupprimer() {
        initComponents();
     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labconfirmation = new javax.swing.JLabel();
        butOui = new javax.swing.JButton();
        butNon = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labconfirmation.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labconfirmation.setText("Voulez-vous vraiment supprimer la Presse ?");

        butOui.setText("OUI");
        butOui.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butOuiActionPerformed(evt);
            }
        });

        butNon.setText("NON");
        butNon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butNonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labconfirmation, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 27, Short.MAX_VALUE)
                        .addComponent(butOui, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(butNon, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(79, 79, 79))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(labconfirmation, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(butOui, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(butNon, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(62, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void abonner(WindowAdapter wa){
        this.addWindowListener(wa);
      
    }
    
    
    private void butOuiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butOuiActionPerformed
      
     Presse p =(Presse) PanelMachine.listPresse.getSelectedValue();
     int numPresse = p.getNumPresse();
    
     if (Tools.isInf(numPresse))
     {
         JOptionPane.showMessageDialog(this, ManagerPresse.supprimerPresse(numPresse));
         this.dispose();
     }
    
    }//GEN-LAST:event_butOuiActionPerformed

    private void butNonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butNonActionPerformed
      this.setVisible(false);
    }//GEN-LAST:event_butNonActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton butNon;
    private javax.swing.JButton butOui;
    private javax.swing.JLabel labconfirmation;
    // End of variables declaration//GEN-END:variables
}
